
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - production=true
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - production=true
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: polls
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: